### PR TITLE
optimization debian package manager tweaks

### PR DESCRIPTION
**Pull request by Rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
Did you test every Dockerfile to make sure that it still works with this change? I am reluctant to accept this PR because it will involve manually testing each Dockerfile.

**Comment by Rajpratik71** [comment]
> Did you test every Dockerfile to make sure that it still works with this change? I am reluctant to accept this PR because it will involve manually testing each Dockerfile.

tested and fixed accordingly

**Comment by Rajpratik71** [comment]
@bruce @technicalpickles @myobie  requesting review

**Comment by kevinbackhouse** [comment]
@Rajpratik71: this seems like a good suggestion for the future, but I am not going to merge this PR because these Dockerfiles work fine as they are and I don't want to spend time testing them again. It is clear from the commit history that you created this PR without testing the changes first and only realized that you had broken them after I posted [this comment](https://github.com/github/securitylab/pull/47#issuecomment-596142102), so I would definitely need to test them myself before I would be comfortable accepting these changes. Also, these Dockerfiles are not used in any production systems, so the slight inefficiency is harmless.

**Pull request closed without merging**
